sudo: required
dist: precise

language: python

python:
- '2.7'

env:
    - CKANVERSION=2.7

services:
    - redis-server
    - postgresql

install:
    - bash bin/travis-build.bash

script: bin/travis-run.sh
